#!/usr/bin/env bash

set -e

if command -v zsh >/dev/null 2>&1; then
    echo "Bootstraping zsh"
    zsh -i -c exit
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if command -v tmux >/dev/null 2>&1; then
    echo "Bootstraping tmux"
    tmux start-server
    tmux new-session -d -s tpm-install && sleep 1
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
    tmux kill-session -t tpm-install
fi

